# This is a basic workflow to help you get started with Actions

name: Building QT app for APP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Qt
      - uses: jurplel/install-qt-action@v2
      
      - name: Use upload build artifact
      - uses: actions/checkout@v2

      - name: Install Qt
      # You may pin to the exact commit or the version.
      # uses: jurplel/install-qt-action@c04feedfdfd6dbe64db62deda57fb0971a1bf440
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/qtproject/src'
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          cached: 'false'
          setup-python: 'true'
          tools-only: 'false'
          extra: '--external 7z'
          
      - uses: actions/upload-artifact@v2
        with:
          name: Upload build for windows
          path: '${{ github.workspace }}/qtproject/src/Qt/$ {{ Qt5_DIR }}/win64_msvc2019_64/bin'
