name: Building QT app for APP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout in my repository
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/qtproject/src'
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          cached: 'false'
          setup-python: 'true'
          tools-only: 'false'
          extra: '--external 7z'
      
      - name: Building the artifact
        uses: actions/upload-artifact@v2
        with:
          name: Upload build for windows
          path: '${{ github.workspace }}/qtproject/src/Qt/${{ Qt5_DIR }}/win64_msvc2019_64/bin'
